export const animationValues = [
  {
    src: "/img7.png",
    scaleFrom: 0.7,
    scaleTo: 5,
    width: 12,
    height: 20,
    top: -20,
    left: 33,
    start: 50,
  },
  {
    src: "/drag/img1.png",
    scaleFrom: 0.7,
    scaleTo: 4,
    width: 10,
    height: 18,
    top: -25,
    left: -5,
    start: 50,
  },
  {
    src: "/drag/img2.png",
    scaleFrom: 0.7,
    scaleTo: 2,
    width: 12, // Corresponds to `width: 8vw`
    height: 20, // Corresponds to `height: 22vh`
    top: -33, // Corresponds to `top: 33vh`
    left: -33, // Corresponds to `left: 33vw`
    start: 100,
  },
  {
    src: "/drag/img3.png",
    scaleFrom: 0.7,
    scaleTo: 3,
    width: 10,
    height: 20,
    top: 33,
    left: 12,
    start: 100,
  },
  {
    src: "/drag/img4.png",
    scaleFrom: 0.7,
    scaleTo: 3,
    width: 12,
    height: 20,
    top: 5,
    left: 25,
    start: 150,
  },
  {
    src: "/drag/img5.png",
    scaleFrom: 0.7,
    scaleTo: 4,
    width: 12,
    height: 20,
    top: 4,
    left: -28,
    start: 150,
  },
  {
    src: "/drag/img6.png",
    scaleFrom: 0.7,
    scaleTo: 4,
    width: 12,
    height: 20,
    top: 22,
    left: 26,
    start: 150,
  },
  {
    src: "/drag/img7.png",
    scaleFrom: 0.7,
    scaleTo: 4,
    width: 12,
    height: 20,
    top: 30,
    left: -25,
    start: 250,
  },
  {
    src: "/drag/img8.png",
    scaleFrom: 0.7,
    scaleTo: 3,
    width: 12,
    height: 20,
    top: 20,
    left: 55,
    start: 250,
  },
  {
    src: "/img7.png",
    scaleFrom: 0.7,
    scaleTo: 5,
    width: 12,
    height: 20,
    top: -20,
    left: 33,
    start: 300,
  },
  {
    src: "/img10.png",
    scaleFrom: 0.7,
    scaleTo: 3.5,
    width: 12,
    height: 20,
    top: 36,
    left: 55,
    start: 350,
  },
  {
    src: "/img11.png",
    scaleFrom: 0.7,
    scaleTo: 2,
    width: 12,
    height: 20,
    top: -11,
    left: 55,
    start: 400,
  },
  {
    src: "/img5.png",
    scaleFrom: 0.7,
    scaleTo: 4,
    width: 12,
    height: 20,
    top: 26,
    left: -12,
    start: 400,
  },
];
