export const values = [
  {
    src: "/img7.png",
    scaleFrom: 0.7,
    scaleTo: 5,
    width: 12,
    height: 20,
    top: 0,
    left: -40,
  },
  {
    src: "/drag/img1.png",
    scaleFrom: 0.7,
    scaleTo: 4,
    width: 10,
    height: 18,
    top: 0,
    left: -20,
  },
  {
    src: "/drag/img2.png",
    scaleFrom: 0.7,
    scaleTo: 2,
    width: 12,
    height: 20, 
    top: 0, 
    left: 0, // Corresponds to `left: 33vw`
  },
  {
    src: "/drag/img3.png",
    scaleFrom: 0.7,
    scaleTo: 3,
    width: 10,
    height: 20,
    top: 0,
    left: 20,
  },
  {
    src: "/drag/img4.png",
    scaleFrom: 0.7,
    scaleTo: 3,
    width: 12,
    height: 20,
    top: 0,
    left: 40,
  },
];
